supabase_url = "https://cqyluuowgrspjobrjlpw.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeWx1dW93Z3JzcGpvYnJqbHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTgzOTEsImV4cCI6MjA2MzA3NDM5MX0.HMQglr2HWJbZJaE_WzGyfqpDjUpHFPtilbrOzi7Uyoo"
